### ISSUE TITLE
A few discrepancies

### ISSUE THREAD

**Issue by legokidlogan** [OverlordAkise/gmod-lua-performance#1]
It's real great to see these perf tests for such commonly-used methods (especially dist/distsqr), though there's a slight hitch:

- **pairs vs ipairs vs for i=1**
  - The test table was set up with `testab[math.random()] = math.random()` instead of `testab[i] = math.random()`, meaning its indices are all floats, causing ipairs and i=1 to have ***0 iterations***. That's not a proper test!
  https://github.com/OverlordAkise/gmod-lua-performance/blob/ee0c6c5d845fd994f51a6d91a52e4a21f1e70e01/files/pairs_vs_ipairs_vs_for.lua#L1-L4
  - It's easy to confirm this with a simple incrementor in each of the loops, to afterwards print the number of iterations for each one. The current test yields 0 iterations for ipairs and i=1.
  - After fixing it to use `testab[i] = math.random()`, I had these results:
  ```
  pairs: 0.0023997000000691
  ipairs: 0.0015596000000642
  i=1: 0.0011977000000343
  ```
  In this test run:
  `i=1` is about 23% faster than `ipairs`, and 50% faster than `pairs`
  `ipairs` is about 35% faster than `pairs`
  However, this was on my instance of GMod, which yielded a much faster `pairs` time than the original test (the only part that should be unchanged), so you'll of course want to retime this on your system for self-consistency.
- **x^2 vs x*x**
  - The prints say `x^x` instead of `x^2`, just a small typo.
  - The code provided is a duplicate of the `local vs global` comparison.
- **table.HasValue(table,x) vs table[x]**
  - While the overall result is still the same (table.HasValue is slow af), keep in mind that this gap widens more and more as the size of the table grows. I agree that it's important for people to recognize the benefit of lookup tables, but this kind of undersells it. The other comparisons are with mostly 'identical' functions, while this is a big-O notation type of situation, specifically O(n) vs O(1).
  - Again, not a huge concern or anything, but it might be nice to put a note somewhere to remind people that `table.HasValue` gets *increasingly* worse with larger tables, while `table[x]` remains at the same fast speed, though with the trade-off of needing extra code setup.

**Comment by OverlordAkise** [comment]
Hi,

Thanks for your feedback!

A bit embarassing to have such mistakes for this long without anybody pointing them out.

I hope i fixed all of the mistakes. I also added a note about the o notation to the table section.

Thanks again!

BR
